/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetmiagel3;

import java.awt.Dimension;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nathan
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() throws FileNotFoundException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelAffichage = new javax.swing.JPanel();
        ListeXXX = new javax.swing.JLabel();
        Retour = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Enregistrer = new javax.swing.JButton();
        PanelAccueil = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AffEmploye = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        AffComp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AffMission = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Gestion de l'entreprise");

        PanelAffichage.setVisible(false);

        ListeXXX.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ListeXXX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ListeXXX.setText("Liste des ?????");

        Retour.setText("Retour");
        Retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetourMouseClicked(evt);
            }
        });
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        jTable2.setVisible(false);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [50][4],
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        Enregistrer.setText("Enregistrer");
        Enregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnregistrerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelAffichageLayout = new javax.swing.GroupLayout(PanelAffichage);
        PanelAffichage.setLayout(PanelAffichageLayout);
        PanelAffichageLayout.setHorizontalGroup(
            PanelAffichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ListeXXX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelAffichageLayout.createSequentialGroup()
                .addGroup(PanelAffichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAffichageLayout.createSequentialGroup()
                        .addContainerGap(550, Short.MAX_VALUE)
                        .addComponent(Retour))
                    .addGroup(PanelAffichageLayout.createSequentialGroup()
                        .addGroup(PanelAffichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAffichageLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAffichageLayout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addComponent(Enregistrer)))
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelAffichageLayout.setVerticalGroup(
            PanelAffichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAffichageLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Retour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListeXXX)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Enregistrer)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Afficher la liste des Employés");

        AffEmploye.setText("Liste Employé");
        AffEmploye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AffEmployeMouseClicked(evt);
            }
        });
        AffEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffEmployeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Afficher la liste des Missions");

        AffComp.setText("Liste Competence");
        AffComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AffCompMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Afficher la liste des Compétences");

        AffMission.setText("Liste Mission");
        AffMission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AffMissionMouseClicked(evt);
            }
        });
        AffMission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffMissionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAccueilLayout = new javax.swing.GroupLayout(PanelAccueil);
        PanelAccueil.setLayout(PanelAccueilLayout);
        PanelAccueilLayout.setHorizontalGroup(
            PanelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelAccueilLayout.createSequentialGroup()
                .addGroup(PanelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAccueilLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(PanelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AffEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelAccueilLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(AffMission, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelAccueilLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(AffComp, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAccueilLayout.setVerticalGroup(
            PanelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAccueilLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AffEmploye)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AffComp)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AffMission)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addContainerGap(139, Short.MAX_VALUE))
            .addComponent(PanelAccueil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelAffichage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(PanelAccueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 57, Short.MAX_VALUE)
                    .addComponent(PanelAffichage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AffMissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffMissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AffMissionActionPerformed

    private void AffEmployeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AffEmployeMouseClicked
        // TODO add your handling code here:
        Entreprise ent;
        try {
            ent = new Entreprise();
            int i = 0;
            
            jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [ent.getListEmp().size()][4],
                new String [] {
                    "Nom", "Prenom", "DateE", "Competence"
                }
            ));
            
            for(Employe e : ent.getListEmp()){
                jTable2.setValueAt(e.getNom(), i, 0);
                jTable2.setValueAt(e.getPrenom(), i, 1);
                jTable2.setValueAt(e.getDateE(), i, 2);
                jTable2.setValueAt(e.getListeComp(), i, 3);
                i++;
            }
            PanelAccueil.setVisible(false);
            PanelAffichage.setVisible(true);
            ListeXXX.setText("Liste des Employés");
            
            jTable2.setVisible(true);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AffEmployeMouseClicked

    private void AffCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AffCompMouseClicked
        // TODO add your handling code here:
        Entreprise ent;
        try {
            ent = new Entreprise();
            int i = 0;
            
            jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [ent.getListComp().size()][2],
                new String [] {
                    "Id", "Fr", "Eng"
                }
            ));
            
            for(Competence c : ent.getListComp()){
                jTable2.setValueAt(c.getId(), i, 0);
                jTable2.setValueAt(c.getLibFr(), i, 1);
                jTable2.setValueAt(c.getLibEng(), i, 2);
                i++;
            }
            PanelAccueil.setVisible(false);
            PanelAffichage.setVisible(true);
            ListeXXX.setText("Liste des Competences");
            jTable2.setVisible(true);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AffCompMouseClicked

    private void AffEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffEmployeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AffEmployeActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RetourActionPerformed

    private void AffMissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AffMissionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AffMissionMouseClicked

    private void RetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetourMouseClicked
        // TODO add your handling code here:
        PanelAffichage.setVisible(false);
        PanelAccueil.setVisible(true);
    }//GEN-LAST:event_RetourMouseClicked

    private void EnregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnregistrerMouseClicked
        try {
            // TODO add your handling code here:
            Entreprise ent = new Entreprise();
            switch(ListeXXX.getText()){
                case "Liste des Employés":
                    ArrayList<Employe> listE = new ArrayList<Employe>();
                    ArrayList<String> listCE = new ArrayList<String>();

                    for(int i=0; i<jTable2.getRowCount(); i++){
                        Employe e = new Employe(i+1, (String)jTable2.getValueAt(i, 1), (String)jTable2.getValueAt(i, 0), (String)jTable2.getValueAt(i, 2));
                        listCE = (ArrayList<String>)jTable2.getValueAt(i, 3);
                        e.setListeComp(listCE);
                        listE.add(e);
                    }
                    ent.sauvegarderEmploye(listE);
                    break;
                case "Liste des Competences":
                    ArrayList<Competence> listC = new ArrayList<Competence>();
                    
                    for(int i=0; i<jTable2.getRowCount(); i++){
                        Competence c = new Competence((String)jTable2.getValueAt(i, 0), (String)jTable2.getValueAt(i, 2), (String)jTable2.getValueAt(i, 1));
                        listC.add(c);
                    }
                    ent.sauvegarderCompetence(listC);
                    break;
                default:
                    break;
            }
            PanelAffichage.setVisible(false);
            PanelAccueil.setVisible(true);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EnregistrerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Accueil a;
                try {
                    a = new Accueil();
                    a.setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AffComp;
    private javax.swing.JButton AffEmploye;
    private javax.swing.JButton AffMission;
    private javax.swing.JButton Enregistrer;
    private javax.swing.JLabel ListeXXX;
    private javax.swing.JPanel PanelAccueil;
    private javax.swing.JPanel PanelAffichage;
    private javax.swing.JButton Retour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
